### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by S4n60w3n** [webscopeio/license.sh#104]
```
[2020-02-28T13:31:49Z] Traceback (most recent call last):
  File "/usr/local/bin/license-sh", line 2, in <module>
    from license_sh import __main__
  File "/usr/local/lib/python3.8/site-packages/license_sh/__main__.py", line 26, in <module>
    run_license_sh(arguments)
  File "/usr/local/lib/python3.8/site-packages/license_sh/commands/run_license_sh.py", line 67, in run_license_sh
    dep_tree = run_check(project_to_check, path, silent, debug)
  File "/usr/local/lib/python3.8/site-packages/license_sh/runners/__init__.py", line 20, in run_check
    return runner(path, silent, debug).check()
  File "/usr/local/lib/python3.8/site-packages/license_sh/runners/npm/__init__.py", line 138, in check
    dep_tree = get_dependency_tree(package_json, all_dependencies)
  File "/usr/local/lib/python3.8/site-packages/license_sh/runners/npm/__init__.py", line 79, in get_dependency_tree
    dependency = package_lock_tree[dep_name]
KeyError: '@fortawesome/fontawesome'
```

**Comment by S4n60w3n** [comment]
Issue is due  #106
