### ISSUE TITLE
Pipenv "--dependencies" issue 

### ISSUE THREAD

**Issue by S4n60w3n** [webscopeio/license.sh#175]
https://github.com/license-test/projectTest

```
[2020-09-10T17:37:07Z] [[pipenv]./Pipfile.lock] Traceback (most recent call last):
  File "/usr/local/bin/license-sh", line 2, in <module>
    from license_sh import __main__
  File "/usr/local/lib/python3.8/site-packages/license_sh/__main__.py", line 28, in <module>
    run_license_sh(arguments)
  File "/usr/local/lib/python3.8/site-packages/license_sh/commands/run_license_sh.py", line 91, in run_license_sh
    analyzed_tree = run_analyze(project_to_check, path, dep_tree)
  File "/usr/local/lib/python3.8/site-packages/license_sh/analyze/__init__.py", line 35, in run_analyze
    return analyzer(path, dep_tree)
  File "/usr/local/lib/python3.8/site-packages/license_sh/analyze/pipenv.py", line 116, in analyze_pipenv
    analyze_dict = get_pipenv_analyze_dict(directory)
  File "/usr/local/lib/python3.8/site-packages/license_sh/analyze/pipenv.py", line 67, in get_pipenv_analyze_dict
    license_data = get_analyze_pipenv_data(directory, dirpath)
  File "/usr/local/lib/python3.8/site-packages/license_sh/analyze/pipenv.py", line 24, in get_analyze_pipenv_data
    requirements_output = subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pipenv'
[[maven]./pom.xml] Traceback (most recent call last):
  File "/usr/local/bin/license-sh", line 2, in <module>
    from license_sh import __main__
  File "/usr/local/lib/python3.8/site-packages/license_sh/__main__.py", line 28, in <module>
    run_license_sh(arguments)
  File "/usr/local/lib/python3.8/site-packages/license_sh/commands/run_license_sh.py", line 91, in run_license_sh
    analyzed_tree = run_analyze(project_to_check, path, dep_tree)
  File "/usr/local/lib/python3.8/site-packages/license_sh/analyze/__init__.py", line 35, in run_analyze
    return analyzer(path, dep_tree)
  File "/usr/local/lib/python3.8/site-packages/license_sh/analyze/maven.py", line 240, in analyze_maven
    licenses_analysis = get_maven_analyze_dict(directory)
  File "/usr/local/lib/python3.8/site-packages/license_sh/analyze/maven.py", line 207, in get_maven_analyze_dict
    license_data = get_analyze_maven_data(directory, dirpath)
  File "/usr/local/lib/python3.8/site-packages/license_sh/analyze/maven.py", line 136, in get_analyze_maven_data
    fetch_maven_licenses(parse_licenses_xml(get_licenses_xml(directory)), license_dir)
  File "/usr/local/lib/python3.8/site-packages/license_sh/analyze/maven.py", line 64, in parse_licenses_xml
    license_url = license_data.find("url").text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by S4n60w3n** [comment]
```
An error has occured.
Unexpected error has occurred.
How to solve it?
Try to re-run the check
Contact our support
[2020-09-17T19:15:09Z] License check failed
[2020-09-17T19:15:10Z] [[pipenv]./Pipfile.lock] Traceback (most recent call last):
  File "/usr/local/bin/license-sh", line 2, in <module>
    from license_sh import __main__
  File "/usr/local/lib/python3.8/site-packages/license_sh/__main__.py", line 28, in <module>
    run_license_sh(arguments)
  File "/usr/local/lib/python3.8/site-packages/license_sh/commands/run_license_sh.py", line 91, in run_license_sh
    analyzed_tree = run_analyze(project_to_check, path, dep_tree)
  File "/usr/local/lib/python3.8/site-packages/license_sh/analyze/__init__.py", line 35, in run_analyze
    return analyzer(path, dep_tree)
  File "/usr/local/lib/python3.8/site-packages/license_sh/analyze/pipenv.py", line 116, in analyze_pipenv
    analyze_dict = get_pipenv_analyze_dict(directory)
  File "/usr/local/lib/python3.8/site-packages/license_sh/analyze/pipenv.py", line 67, in get_pipenv_analyze_dict
    license_data = get_analyze_pipenv_data(directory, dirpath)
  File "/usr/local/lib/python3.8/site-packages/license_sh/analyze/pipenv.py", line 24, in get_analyze_pipenv_data
    requirements_output = subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pipenv'
```
