### ISSUE TITLE
Yarn issue

### ISSUE THREAD

**Issue by 4rokis** [webscopeio/license.sh#24]
S4n60w3n/phaser/master/9db9511bf106c0e9f7523b1b2d32eaf35ad322d3
```
Traceback (most recent call last):
  File "/usr/local/bin/license-sh", line 69, in <module>
    dep_tree, license_map = runner.check()
  File "/usr/local/lib/python3.8/site-packages/license_sh/runners/yarn/__init__.py", line 332, in check
    dep_tree = get_dependency_tree(flat_tree, package_json, package_map)
  File "/usr/local/lib/python3.8/site-packages/license_sh/runners/yarn/__init__.py", line 283, in get_dependency_tree
    version=dependency.get("version"),
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by S4n60w3n** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/license-sh", line 69, in <module>
    dep_tree, license_map = runner.check()
  File "/usr/local/lib/python3.8/site-packages/license_sh/runners/yarn/__init__.py", line 337, in check
    license_map = fetch_npm_licenses(flat_dependencies)
  File "/usr/local/lib/python3.8/site-packages/license_sh/runners/runners_shared.py", line 11, in fetch_npm_licenses
    urls = [
  File "/usr/local/lib/python3.8/site-packages/license_sh/runners/runners_shared.py", line 13, in <listcomp>
    for dependency, version in all_dependencies
ValueError: too many values to unpack (expected 2)
```
