### ISSUE TITLE
No such file or directory: 'yarn': 'yarn'

### ISSUE THREAD

**Issue by S4n60w3n** [webscopeio/license.sh#74]
```
[theodore@milacik license.sh]$ license-sh --version
1.0.15
```
```
[theodore@milacik license.sh]$ license-sh ../devenv/
===========
Initiated License.sh check for YARN project devenv located at ../devenv/
===========
Traceback (most recent call last):
  File "/usr/bin/license-sh", line 2, in <module>
    from license_sh import __main__
  File "/usr/lib/python3.7/site-packages/license_sh/__main__.py", line 24, in <module>
    run_license_sh(arguments)
  File "/usr/lib/python3.7/site-packages/license_sh/commands/run_license_sh.py", line 68, in run_license_sh
    dep_tree, license_map = runner.check()
  File "/usr/lib/python3.7/site-packages/license_sh/runners/yarn/__init__.py", line 336, in check
    package_map = parse_yarn_lock(get_yarn_lock_json(self.directory))
  File "/usr/lib/python3.7/site-packages/license_sh/runners/yarn/__init__.py", line 58, in get_yarn_lock_json
    stderr=subprocess.PIPE,
  File "/usr/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'yarn': 'yarn'
```

**Comment by S4n60w3n** [comment]
@jvorcak Can you please verify that you can reproduce it? 

repo:
https://github.com/license-test/devenv

**Comment by S4n60w3n** [comment]
Probably some system specific issue as docker image works fine
