### ISSUE TITLE
Package-lock without dependencies

### ISSUE THREAD

**Issue by S4n60w3n** [webscopeio/license.sh#75]
```
===========
Initiated License.sh check for pipenv project located at ../*****
===========
Traceback (most recent call last):
  File "/usr/bin/license-sh", line 2, in <module>
    from license_sh import __main__
  File "/usr/lib/python3.8/site-packages/license_sh/__main__.py", line 24, in <module>
    run_license_sh(arguments)
  File "/usr/lib/python3.8/site-packages/license_sh/commands/run_license_sh.py", line 58, in run_license_sh
    dep_tree, license_map = runner.check()
  File "/usr/lib/python3.8/site-packages/license_sh/runners/npm/__init__.py", line 121, in check
    all_dependencies = package_lock["dependencies"]
KeyError: 'dependencies'

```

**Comment by S4n60w3n** [comment]
Already fixed, closing
